const DEFAULT__PRODUCTS = [
  {
    id: 1,
    name: "HP 245 G10 R5-7520U",
    currentPrice: 10790000,
    oldPrice: "13.000.000",
    imageUrl: "/img/productItem1.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "14 inch",
      "Intel UHD graphic",
      "Ổ cứng 8GB",
      "Dung lượng 256GB",
      "Cân nặng 1.36kg",
    ],
  },
  {
    id: 2,
    name: "DELL 200 G10 Gaming",
    currentPrice: 12790000,
    oldPrice: "13.000.000",
    imageUrl: "/img/productItem2.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "16 inch",
      "Intel SSH graphic",
      "Ổ cứng 16GB",
      "Dung lượng 128GB",
      "Cân nặng 1.5kg",
    ],
  },
  {
    id: 3,
    name: "ASUS 200 G10 Gaming",
    currentPrice: 8790000,
    oldPrice: "13.000.000",
    imageUrl: "/img/productItem3.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "16 inch",
      "Intel SSH graphic",
      "Ổ cứng 16GB",
      "Dung lượng 128GB",
      "Cân nặng 1.5kg",
    ],
  },
  {
    id: 4,
    name: "MACBOOK 200 G10 Gaming",
    currentPrice: 25790000,
    oldPrice: "13.000.000đ",
    imageUrl: "/img/productItem4.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "16 inch",
      "Intel SSH graphic",
      "Ổ cứng 16GB",
      "Dung lượng 128GB",
      "Cân nặng 1.5kg",
    ],
  },
  {
    id: 5,
    name: "LG 200 G10 Gaming",
    currentPrice: 18790000,
    oldPrice: "13.000.000đ",
    imageUrl: "/img/productItem1.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "16 inch",
      "Intel SSH graphic",
      "Ổ cứng 16GB",
      "Dung lượng 128GB",
      "Cân nặng 1.5kg",
    ],
  },
  {
    id: 6,
    name: "RAZER 200 G10 Gaming",
    currentPrice: 11790000,
    oldPrice: "13.000.000đ",
    imageUrl: "/img/productItem6.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "16 inch",
      "Intel SSH graphic",
      "Ổ cứng 16GB",
      "Dung lượng 128GB",
      "Cân nặng 1.5kg",
    ],
  },

  {
    id: 7,
    name: "RAZER 200 G10 Gaming",
    currentPrice: 12790000,
    oldPrice: "13.000.000đ",
    imageUrl: "/img/productItem6.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "16 inch",
      "Intel SSH graphic",
      "Ổ cứng 16GB",
      "Dung lượng 128GB",
      "Cân nặng 1.5kg",
    ],
  },
  {
    id: 8,
    name: "HP 200 G10 Gaming",
    currentPrice: 26790000,
    oldPrice: "25.000.000",
    imageUrl: "/img/productItem6.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "16 inch",
      "Intel SSH graphic",
      "Ổ cứng 16GB",
      "Dung lượng 256GB",
      "Cân nặng 1.5kg",
    ],
  },
  {
    id: 9,
    name: "HP 200 G10 Gaming",
    currentPrice: 11790000,
    oldPrice: "12.000.000đ",
    imageUrl: "/img/productItem6.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "16 inch",
      "Intel SSH graphic",
      "Ổ cứng 16GB",
      "Dung lượng 256GB",
      "Cân nặng 1.5kg",
    ],
  },
  {
    id: 10,
    name: "HP 200 G10 Gaming",
    currentPrice: 11790000,
    oldPrice: "12.000.000đ",
    imageUrl: "/img/productItem6.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "16 inch",
      "Intel SSH graphic",
      "Ổ cứng 16GB",
      "Dung lượng 256GB",
      "Cân nặng 1.5kg",
    ],
  },
  {
    id: 11,
    name: "HP 200 G10 Gaming",
    currentPrice: 11790000,
    oldPrice: "12.000.000đ",
    imageUrl: "/img/productItem6.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "16 inch",
      "Intel SSH graphic",
      "Ổ cứng 16GB",
      "Dung lượng 256GB",
      "Cân nặng 1.5kg",
    ],
  },
  {
    id: 12,
    name: "HP 200 G10 Gaming",
    currentPrice: 11790000,
    oldPrice: "12.000.000đ",
    imageUrl: "/img/productItem6.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "16 inch",
      "Intel SSH graphic",
      "Ổ cứng 16GB",
      "Dung lượng 256GB",
      "Cân nặng 1.5kg",
    ],
  },
  {
    id: 13,
    name: "HP 200 G10 Gaming",
    currentPrice: 11790000,
    oldPrice: "12.000.000đ",
    imageUrl: "/img/productItem6.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "16 inch",
      "Intel SSH graphic",
      "Ổ cứng 16GB",
      "Dung lượng 256GB",
      "Cân nặng 1.5kg",
    ],
  },
  {
    id: 14,
    name: "HP 200 G10 Gaming",
    currentPrice: 11790000,
    oldPrice: "12.000.000đ",
    imageUrl: "/img/productItem6.webp",
    backgroundUrl: "/img/backGround.webp",
    config: [
      "16 inch",
      "Intel SSH graphic",
      "Ổ cứng 16GB",
      "Dung lượng 256GB",
      "Cân nặng 1.5kg",
    ],
  },
];


export default DEFAULT__PRODUCTS;